apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170662520
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170662520
    app.kubernetes.io/part-of: test-app-170662520
  name: java-quarkus-170662520
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170662520
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170662520
    spec:
      containers:
      - image: quay.io/hacdev/cwydlpkw-tenant/test-app-170662520/java-quarkus-170662520@sha256:e4685daaceb9fd8c80b3b60349ba96262791b3a8bda3259bd2f031960d5862dd
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
